apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "money.api.fullname" . }}
  labels:
    {{- include "money.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "money.selectorLabels" (dict "ctx" . "component" "api") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "money.selectorLabels" (dict "ctx" . "component" "api") | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            {{- include "money.appEnv" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
