apiVersion: v1
kind: Service
metadata:
  name: {{ include "money.web.fullname" . }}
  labels:
    {{- include "money.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "money.selectorLabels" (dict "ctx" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.web.port }}
